#!/usr/bin/env bash

echo "* Starting deployment of WDT discourse app"

GIT_DIR=$(pwd)
cd ..

export RAILS_ENV=`git branch | grep '*' | awk '{print $2}' `

source /usr/local/rvm/scripts/rvm
source .rvmrc

echo "rvm current"
rvm current

echo "* Deploying on $RAILS_ENV"

echo "* checkout head"
env -i git reset --hard

echo '* deploy gems'
bundle install --without development test --deployment

echo '* rake db:migrate'
bundle exec rake db:migrate

echo '* compiling assets'
bundle exec rake assets:precompile

# echo '* restart webserver'
# [[ -f tmp/pids/puma.pid ]] && env -i sv restart discourse_app
